### ISSUE TITLE
Failed to load notebook unconstrained.jmd

### ISSUE THREAD

**Issue by f6v** [MichielStock/STMO#17]
I get an error when opening unconstrained.jmd with Pluto.

> Error message:
> 
> File is not a Pluto.jl notebook
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] load_notebook_nobackup(::IOStream, ::String) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/notebook/Notebook.jl:119
>  [3] #21 at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/notebook/Notebook.jl:170 [inlined]
>  [4] open(::Pluto.var"#21#22"{String}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:325
>  [5] open at ./io.jl:323 [inlined]
>  [6] load_notebook_nobackup(::String) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/notebook/Notebook.jl:169
>  [7] load_notebook(::String, ::Bool) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/notebook/Notebook.jl:186
>  [8] open(::Pluto.ServerSession, ::String; run_async::Bool, compiler_options::Nothing) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/SessionActions.jl:21
>  [9] open at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/SessionActions.jl:15 [inlined]
>  [10] (::Pluto.var"#try_launch_notebook_response#113"{Pluto.var"#try_launch_notebook_response#94#114"{Pluto.ServerSession}})(::typeof(Pluto.SessionActions.open), ::String; title::String, advice::String, home_url::String) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/Static.jl:137
>  [11] (::Pluto.var"#96#116")(::HTTP.Messages.Request) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/Static.jl:166
>  [12] (::Pluto.var"#84#102"{Bool,Pluto.var"#96#116",Pluto.ServerSession,Pluto.var"#add_set_secret_cookie!#99"{Pluto.ServerSession}})(::HTTP.Messages.Request) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/Static.jl:101
>  [13] handle(::HTTP.Handlers.RequestHandlerFunction{Pluto.var"#84#102"{Bool,Pluto.var"#96#116",Pluto.ServerSession,Pluto.var"#add_set_secret_cookie!#99"{Pluto.ServerSession}}}, ::HTTP.Messages.Request) at /Users/f6v/.julia/packages/HTTP/IAI92/src/Handlers.jl:253
>  [14] handle(::HTTP.Handlers.Router{Symbol("##253")}, ::HTTP.Messages.Request) at /Users/f6v/.julia/packages/HTTP/IAI92/src/Handlers.jl:467
>  [15] (::Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/f6v/.julia/packages/Pluto/R8t0Y/src/webserver/WebServer.jl:210
>  [16] handle at /Users/f6v/.julia/packages/HTTP/IAI92/src/Handlers.jl:269 [inlined]
>  [17] #4 at /Users/f6v/.julia/packages/HTTP/IAI92/src/Handlers.jl:345 [inlined]
>  [18] macro expansion at /Users/f6v/.julia/packages/HTTP/IAI92/src/Servers.jl:367 [inlined]
>  [19] (::HTTP.Servers.var"#13#14"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:356

Julia: 1.5.1
Pluto: 0.12.3
macOS: 10.15.7

**Comment by MichielStock** [comment]
Hi Igor,

jmd format stands for [Julia markdown](https://weavejl.mpastell.com/stable/) and has nothing to do with Pluto. I use these to write the notes and use the build.jl file to transform them into jupyter notebooks (on Github) and pdf (on Ufora). These are mainly for my own convenience and not really important for you.
Except for autodiff, all exercises are in jupyter notebook.

Michiel

**Comment by f6v** [comment]
Ah ok, thanks.
